### PR TITLE
Adds a new demo image to resources

### PR DESCRIPTION
**Pull request by henningkayser**
This is an updated image that can be used for the tutorial and or README

### CODE REVIEW

**Comment by mlautman** [comment]
Is this used somewhere?

**Comment by henningkayser** [comment]
@davetcoleman suggested it for the tutorial (https://github.com/PickNikRobotics/moveit_tutorials/pull/1#discussion_r263594623) and since the other images are stored here as well I thought we could just add it.
We could of course also add it to https://github.com/ros-planning/moveit_tutorials/pull/302 directly.

**Comment by rhaschke** [comment]
The images in resources are used for README.md. If you want to use the image in the tutorial, you should add it to the tutorial.

**Comment by henningkayser** [comment]
> The images in resources are used for README.md. If you want to use the image in the tutorial, you should add it to the tutorial.

@rhaschke I agree. It's just that the same 'old' image used in the tutorial is also used in the README. I suggest adding a new one here and change both.

**Comment by rhaschke** [comment]
The key is that the tutorial should be self-contained. You cannot refer to images in another repo, can you?

**Comment by henningkayser** [comment]
You can use raw file links for images so it doesn't matter in which repo the image is.

**Comment by rhaschke** [comment]
I consider it really bad practice to reference a (required) resource outside the tutorial package.
In future, nobody will remember that the image is referenced from the tutorial, but eventually is not used here anymore, so we easily are tempted to remove the image here.

**Pull request closed without merging**
