### PR TITLE
Cleanup demos with better documentation

### PR DESCRIPTION
**Pull request by davetcoleman**
- Remove unused variables
- Fix incorrect comments
- Rename setIdealTCPGraspPose() and deprecate old name

### CODE REVIEW

**Comment by mlautman** [comment]
@davetcoleman This should have targeted master

**Comment by mlautman** [comment]
Also this introduces a bug. Reverting and making a new PR.

**Comment by mlautman** [comment]
#57

**Comment by davetcoleman** [comment]
When was master created? It wasn't available yet (see https://github.com/ros-planning/moveit_grasps/issues/52) when I created this...

**Pull request merged**
